### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by toadragethe5th** [mewmix/bleak-dash#1]
Hi!

I can't connect to my dash bot. I quit out after multiple failed attempts. Any ideas?

**Comment by mewmix** [comment]
Hi thank you for trying this out. What are your system specs? Also is your dash robot named "dash" or did you change the name? 

If you changed the name take a look at the function below and modify it in dash/robot.py

```
async def discover_and_connect(retry_attempts=3, retry_delay=5):
    attempt = 0
    while attempt < retry_attempts:
        attempt += 1
        logging.info(f"Discovery attempt {attempt} of {retry_attempts}")
        try:
            devices = await BleakScanner.discover()
            for device in devices:
                if device.name == "Dash": <----------- Change the name here!
                    logging.info(f"Found Dash at: {device.address}")
                    dash_robot = DashRobot(device.address)
                    await dash_robot.connect()
                    return dash_robot
                elif device.name == "Dot":
                    logging.info(f"Found Dot at: {device.address}")
                    dot_robot = Robot(device.address)
                    await dot_robot.connect()
                    return dot_robot
            logging.warning("Compatible device not found. Retrying...")
        except Exception as e:
            logging.error(f"An error occurred during device discovery: {e}")
        await asyncio.sleep(retry_delay)
    logging.error("Failed to discover device after multiple attempts.")
    return None
```
Once you've made that change you can navigate to the project directory and perform a `pip install . -e` (make sure you uninstall the package first!)

**Comment by toadragethe5th** [comment]
I fixed the problem, it just involved renaming dash. Also, are you planning on implementing sensor usage? If I had a little documentation on what the sensor details are, I could implement it myself.

**Comment by toadragethe5th** [comment]
Also the unfortunate thing with this is that if you aren't using pygatt, you are going to have a really hard time gathering events and values from the robot itself.

**Comment by mewmix** [comment]
For [sensors](https://github.com/IlyaSukhanov/morseapi/blob/master/morseapi/sensors.py) this is the original code that was adapted from. I have not ported yet. Feel free to open a pull request. 

With regards to pygatt - I didn't find the library to be as cross-platform friendly but will be happy to do some more research.

**Comment by mewmix** [comment]
Closing this out for now! Reopen as you see fit!
