### ISSUE TITLE
Integrating Dash and Dot's sensors

### ISSUE THREAD

**Issue by accountrev** [mewmix/bleak-dash#3]
Hello. I came across this repo a bit ago after looking up ways on how to run custom code to my Dash. I found mine recently after years of not using it, and I thought it would be a nice little side project to do.

I realized that there isn't any support for the sensors, buttons, or sound recognition for the Dash here, but you happened to say it is possible to port it over from morseapi on this closed issue - https://github.com/mewmix/bleak-dash/issues/1#issuecomment-2065497604. 

So I took some time to properly port it over and it works well. I am able to see my robot's rotations, button presses, etc. 
Although, I am not sure how I implemented it is correct as I am very inexperienced with using Bleak and asyncio (it was somewhat easy but I'm still not confident lol).

I see that you are still active on this repo, so my question is **are you still in need of sensor integration?** I do not want to interfere with your current progress and I'm not sure if you plan to push an update soon for this.

**Comment by axiomfolly** [comment]
I'm not the owner of this repo, but also interested in the project. Your additions sound promising and I would be curious how you've done that.

Might I be so bold to suggest creating a PR? This way the owner of the git can check if your solution is up to standards when time allows it, and in the meantime it gives other people a way to access/contribute on what you've created :)

Thanks for considering.

**Comment by accountrev** [comment]
I have created a pull request, you can view it here: #4

**Comment by mewmix** [comment]
Great. I owe the other issue some logs but I broke my laptop so have been away. What a wonderful surprise to see your PR. Will review and test tonight thank you ☺️

**Comment by accountrev** [comment]
Thanks for accepting the pull request!
